- name: Managing kubernetes cluster
  hosts: servers

  tasks:
  - name: Get a list of all pods from any namespace
    k8s_info:
      kind: Pod
      namespace: "{{ namespace | default('default') }}"
    register: pod_list